1 map
FryOS/js-test-1 pull request #21
Opened 2023-06-30 21:27 UTC by FryOS

2023-07-04 06:05 UTC, Grinv requested changes

2023-07-04 06:05 UTC, Grinv commented on 1-map/map.js
> +
Я бы всё-таки советовал сделать новый репозиторий. Это всё-таки новый курс, новая сущность, лучше не сгребать всё в кучу.
Но уже ладно, проведём этот курс в этом репозитории.

2023-07-04 06:05 UTC, Grinv commented on 1-map/map.js
> +const uniqueArrId = Array.from(new Set(arr.map((obj) => obj.id))).map((id) => {
В данном случае если мы выбираем между количеством символов и читабельностью, предпочтительнее читабельность. Если потом всё через сборщик пропускать, babel всеравно всё порежет, но читабельность очень страдает.
Советую разбирать на несколько операций.

2023-07-04 06:05 UTC, Grinv commented on 1-map/map.js
> +const uniqueArrId = Array.from(new Set(arr.map((obj) => obj.id))).map((id) => {
Лучше такие вещи делать переиспользуемыми. Обернуть в функцию и возвращать результат. В реальным проектах нам скорее всего захотелось бы переместить её в `utils` и потом использовать для других мест.

2023-07-04 06:05 UTC, Grinv commented on 1-map/map.js
> +  return arr.find((obj) => obj.name === name);
Ничего не замечаешь общего с функцией `uniqueArrId`? Они ж абсолютные копии, кроме одной переменной) Тут лучше её передавать в функцию и тогда у тебя 2 функции, которые делают одно и тоже схлопнутся в одну.

2023-07-04 06:05 UTC, Grinv commented on 1-map/map.js
> +});
Вообще по заданию тебе надо убрать ПОЛНЫЕ дубликаты, т.е. где все поля совпадают. Запись типа
```javascript
const dublicatesArray = [
   {id: 1, name: 'Вася'},
   {id: 1, name: 'Вася'}
];
```
Подумай, как это сделать за один проход, не сравнивая каждое поле по отдельности.

2023-07-05 20:59 UTC, FryOS commented on 1-map/map.js
> +  return arr.find((obj) => obj.name === name);
сделал.

2023-07-05 20:59 UTC, FryOS commented on 1-map/map.js
> +});
Да. Оно так и работает.

2023-07-06 15:33 UTC, Grinv commented on 1-map/map.js
> +});
Нет, оно работает не так. Сейчас ты ищешь по каждому отдельному полю. Если добавится ещё одно поле, надо будет добавить ещё один метод. Нужно исключить записи, которые дублируются по всем полям сразу.
Представь, что у нас в записи не 2 поля, а 20, мы ж не будем искать по каждому полю отдельно.

2023-07-06 15:35 UTC, Grinv requested changes

2023-07-06 15:35 UTC, Grinv commented on 1-map/map.js
> +console.log(uniqueArr(arr1, "name"));
В метод мы должны передавать только массив с данными. Уникализация происходит, если ВСЕ параметры в записи дублируются одновременно. И представь, что у нас не 2, а 20 записей. Это можно сделать одним методом.
Спойлер: `JSON.stringify`

2023-07-06 15:35 UTC, Grinv commented
И удали пожалуйста Диму из ревьюверов

2023-07-06 20:43 UTC, FryOS commented on 1-map/map.js
> +console.log(uniqueArr(arr1, "name"));
Вот тут не ясно. в задании указано что надо убрать id 1. Надо делать как говорит автор или как говорит ментор? И да я что-то не понял как это сделать если использовать JSON.stringify
О чем идет речь?

2023-07-08 14:42 UTC, Grinv commented on 1-map/map.js
> +console.log(uniqueArr(arr1, "name"));
Да, но Антон там больше для примера сказал, что значит уникализация)
Но согласен, не очень однозначно и можно по разному трактовать) Но упражнение там направленно именно на работу с Set и подготовить данные так, чтоб помочь Set самому убрать дубликаты. Иначе какой смысл впрнципе заворачивать данные в Set, а потом обратно преобразовывать в массив? Могли бы просто в массиве оставить. А ты поймёшь это, когда воспользуешься JSON.stringify.

Просто представь, что допустим id нет, и тебе просто надо убрать дубликаты объектов.

2023-07-09 15:35 UTC, FryOS commented on 1-map/map.js
> +console.log(uniqueArr(arr1, "name"));
Я как понимаю суть в том чтобы потренироваться с сетами и мапами
У меня вышло вот так. Но я все же пока не понял как не указывать поле, если их 20 предположим. 
JSON.stringify ясно для чего нужен. 
не ясно что вы имели ввиду

2023-07-10 09:27 UTC, Grinv approved these changes

2023-07-10 09:27 UTC, Grinv commented on 1-map/map.js
> +console.log(uniqueArr(arr1, "name"));
> Я как понимаю суть в том чтобы потренироваться с сетами и мапами

Всё правильно, я так и написал.

> У меня вышло вот так. Но я все же пока не понял как не указывать поле, если их 20 предположим.
JSON.stringify ясно для чего нужен.

Сами себе противоречите. Не понимаете, как не указывать 20 полей, но понимает, для чего JSON.stringify. JSON.stringify как раз и нужен, чтоб не указывать 20 полей :)

Хорошо, если вас устраивает ваше решение и не нравится, что я вам предлагаю, тогда я приму ваше.

2023-07-10 09:27 UTC, merged