2 dice
FryOS/js-test-1 pull request #22
Opened 2023-06-30 21:27 UTC by FryOS

2023-07-04 06:12 UTC, Grinv requested changes

2023-07-04 06:12 UTC, Grinv commented on app/app.js
> +}
Вот тут молодец, что сделал универсальную переиспользуемую функцию👍

2023-07-04 06:12 UTC, Grinv commented on app/app.js
> +console.log(dice(6));
Названия функций начинаются с глагола. `doSomething`, `getSomething`, `unifySomething`, `checkSomething`.
В данном случае можешь назвать её просто `play`.

2023-07-04 06:12 UTC, Grinv commented on app/app.js
> +      return random(min, dice);
Все эти условия можно свернуть просто в один вызов функции.
Для этого тебе просто в саму функцию play надо передавать названия кубика.
Как помнишь, они называются `d4`, `d8`, `d12`. Нужно просто достать количество сторон из названия кубика. Это и будет наш `max`, а `min` у нас не меняется.

2023-07-04 06:13 UTC, Grinv requested changes

2023-07-04 06:13 UTC, Grinv commented on app/app.js
> +function dice(dice) {
Функция `dice` в которую передаётся `dice`? Не надо так :/

2023-07-04 20:23 UTC, FryOS commented on app/app.js
> +      return random(min, dice);
Не понял. =(

2023-07-05 21:00 UTC, FryOS commented on app/app.js
> +console.log(dice(6));
play

2023-07-05 21:08 UTC, FryOS commented on app/app.js
> +      return random(min, dice);
вроде понял

2023-07-05 21:08 UTC, FryOS commented on app/app.js
> +function dice(dice) {
исправил

2023-07-06 15:46 UTC, Grinv requested changes

2023-07-06 15:46 UTC, Grinv commented on app/app.js
> +      return random(min, Number(dice.substring(1)));
У тебя ж одно и тоже в каждом case происходит, зачем switch тогда?)) 
```javascript
const diceSidesAmount = Number(dice.substring(1));
return random(min, diceSidesAmount);
```
и всё, весь switch уходит

2023-07-06 21:16 UTC, FryOS commented on app/app.js
> +      return random(min, Number(dice.substring(1)));
Это точно работает =)

2023-07-08 14:47 UTC, Grinv approved these changes

2023-07-10 09:30 UTC, Grinv commented
Нуу, вообще конфкликты не так резолвятся  :( Почему задание то в `/app.js`
В задании было указано, что нужно сделать папку 1-dice и там уже делать задание. Ну ладно.

2023-07-10 09:30 UTC, merged