3 birthday
FryOS/js-test-1 pull request #23
Opened 2023-07-03 20:01 UTC by FryOS

2023-07-04 06:27 UTC, Grinv requested changes

2023-07-04 06:27 UTC, Grinv commented on birthday/app.js
> +const dateNow = new Date(Date.now());
В данном случае у тебя у тебя dateNow определится в самом начале, когда будет загрузка скрипта и интерпретатор пройдётся по всем импортированным файлам.
Что будет если ты загрузил скрипт, но он у тебя висит пару дней и ты только через пару дней вызвал функцию validateBirthday? dateNow у нас останется старым. неактуальным и не валидным. Поэтому тут лучше определять dateNow именно в момент вызова функции, чтоб он был актуальным.

2023-07-04 06:27 UTC, Grinv commented on birthday/app.js
> +    (dateNow - new Date(birthday)) / (1000 * 60 * 60 * 24 * 30 * 12)
Лучше такие "магические" числа класть в константы, чтоб другие разработчики понимали, которые читают код, понимали, что это за число и что оно взято не с потолка. Опять же, оно у тебя не меняется и можно его вынести за функцию
```javascript
const YEAR_IN_MILLISECONDS = 1000 * 60 * 60 * 24 * 30 * 12;

2023-07-04 06:27 UTC, Grinv commented on birthday/app.js
> +    true;
Что значит эта запись? Она ж просто не работает.

2023-07-04 06:27 UTC, Grinv commented on birthday/app.js
> +  }
Тут вспоминаем про принцип KISS (Keep it simple, stupid)
У тебя во что превращается сравнение? В boolean. Ну так и верни его)
И запись
```javascript
if (age <= 18) {
    return false;
} else {
    true;
}
```
превратится в 
```javascript
return age <= 18;
```
По-моему, так гораздо читабельнее и проще.

2023-07-04 06:32 UTC, Grinv commented
<img width="440" alt="Screenshot 2023-07-04 at 14 29 16" src="https://github.com/FryOS/js-test-1/assets/4070730/d1513bc8-6b26-4e05-8468-12c1efe47b9f">
Не надо так делать. У тебя ветки абсолютно никак друг с другом не связаны. Таким образом ты сам создаёшь для себя кучу проблем с резолвом конфликтов в дальнейшем и доп. сайд эффектами. Ветки должны выходить из одной коренной ветки `master` или `develop`, но никак не друг из друга.

![Screenshot 2023-07-04 at 14 32 21](https://github.com/FryOS/js-test-1/assets/4070730/a7ce19f8-7f8e-4f4a-aa0e-d618637b920f)

2023-07-04 20:24 UTC, FryOS commented on birthday/app.js
> +const dateNow = new Date(Date.now());
dateNow  перенести внутрь функции?

2023-07-04 20:25 UTC, FryOS commented on birthday/app.js
> +    true;
почему? Работает =) Я же проверял. там я return мог забыть

2023-07-05 21:15 UTC, FryOS commented on birthday/app.js
> +  }
cсделал

2023-07-06 15:47 UTC, Grinv commented on birthday/app.js
> +const dateNow = new Date(Date.now());
Да, конечно, тебе ж нужно иметь актуальный dateNow именно на момент вызова функции.

2023-07-06 15:48 UTC, Grinv commented on birthday/app.js
> +    true;
Ну вот я про return и говорю. False возвращаем, а true почему-то нет)

2023-07-06 15:51 UTC, Grinv requested changes

2023-07-06 15:51 UTC, Grinv commented on birthday/app.js
> +  const dateNow = new Date(Date.now());
Да, всё хорошо. Только тут `Date.now()` излишен. Просто `new Date()` сделает тоже самое.
```javascript
const dateNow = new Date();

2023-07-06 21:17 UTC, FryOS commented on birthday/app.js
> +const dateNow = new Date(Date.now());
сделал

2023-07-06 21:17 UTC, FryOS commented on birthday/app.js
> +    (dateNow - new Date(birthday)) / (1000 * 60 * 60 * 24 * 30 * 12)
вынес

2023-07-06 21:19 UTC, FryOS commented on birthday/app.js
> +  const dateNow = new Date(Date.now());
хм...и правда

2023-07-08 14:46 UTC, Grinv approved these changes

2023-07-08 14:46 UTC, merged