До нового года осталось
FryOS/js-test-1 pull request #24
Opened 2023-07-06 20:27 UTC by FryOS

2023-07-08 15:27 UTC, Grinv requested changes

2023-07-08 15:27 UTC, Grinv commented on 4-timer/app.js
> +  const days = Math.floor(diff / YEAR_IN_DAYS) % 30;
Тут расчёт надо будет поменять. В месяце может быть и 31 день и 28.

2023-07-08 15:27 UTC, Grinv commented on 4-timer/app.js
> +  const YEAR_IN_SECONDS = 1000;
Эти константы постоянные, нет необходимости каждый раз им давать значение при каждом вызове функции.

2023-07-08 15:27 UTC, Grinv commented on 4-timer/app.js
> +  const newYear = new Date(now.getFullYear() + 1, 0, 1);
Дата нового года рассчитывается тоже один раз, поэтому можно вынести за функцию.

2023-07-08 15:27 UTC, Grinv commented on 4-timer/app.js
> +  document.getElementById("countdown").textContent = countdown;
Тоже нет необходимости селектить каждый раз элемент, лишнее действие, выносим за функцию
```javascript
const countdownElement = document.getElementById("countdown");

function updateCountdown() {
  countdownElement.textContent = countdown;

2023-07-08 15:27 UTC, Grinv commented on 4-timer/app.js
> +setInterval(updateCountdown, 1000);
Нужно будет остановить таймер, когда мы достигаем даты нового года.

2023-07-08 15:32 UTC, Grinv requested changes

2023-07-08 15:32 UTC, Grinv commented on 4-timer/app.js
> +  const YEAR_IN_MOUNTHS = 1000 * 60 * 60 * 24 * 30;
В году 30 дней?) Тут все константы неправильно названы. Эта например должна быть `MONTH_IN_MILLISECONDS`

2023-07-08 15:32 UTC, Grinv commented on 4-timer/app.js
> +  const YEAR_IN_DAYS = 1000 * 60 * 60 * 24;
Эта `DAY_IN_MILLISECONDS`

И т.д.

2023-07-09 15:52 UTC, FryOS commented on 4-timer/app.js
> +  const YEAR_IN_SECONDS = 1000;
Так вы же сами сказали выносить их. А теперь не выносить. Как такое понимать?

2023-07-09 16:03 UTC, FryOS commented on 4-timer/app.js
> +  const newYear = new Date(now.getFullYear() + 1, 0, 1);
вынес

2023-07-09 16:03 UTC, FryOS commented on 4-timer/app.js
> +  document.getElementById("countdown").textContent = countdown;
вынес

2023-07-09 16:27 UTC, FryOS commented on 4-timer/app.js
> +  const newYear = new Date(now.getFullYear() + 1, 0, 1);
Оно так не работает тогда. Не обновляется.

2023-07-09 16:28 UTC, FryOS commented on 4-timer/app.js
> +  const YEAR_IN_MOUNTHS = 1000 * 60 * 60 * 24 * 30;
надо тогда вовсе переделывать и высчитывать высокосный или нет

2023-07-10 09:18 UTC, Grinv requested changes

2023-07-10 09:18 UTC, Grinv commented on 4-timer/app.js
> +  const YEAR_IN_MOUNTHS = 1000 * 60 * 60 * 24 * 30;
Да, это тоже надо учитывать.

2023-07-10 09:18 UTC, Grinv commented on 4-timer/app.js
> +  const YEAR_IN_SECONDS = 1000;
Я тут что-то писал про "не выносить"? Нет. Я написал "нет необходимости каждый раз им давать значение при каждом вызове" - это значит, что им задать значение надо только один раз, ибо оно не меняется. А возможно где-то может переиспользоваться.

2023-07-10 09:18 UTC, Grinv commented on 4-timer/app.js
> +  const newYear = new Date(now.getFullYear() + 1, 0, 1);
Дата нового года и не должна обновляться. Обсудили в Discord

2023-07-11 19:57 UTC, FryOS commented on 4-timer/app.js
> +  const YEAR_IN_SECONDS = 1000;
не совсем понятна идея. что именно не так я сделал =(

2023-07-11 19:58 UTC, FryOS commented on 4-timer/app.js
> +  const newYear = new Date(now.getFullYear() + 1, 0, 1);
вынес. понял.

2023-07-11 20:35 UTC, FryOS commented on 4-timer/app.js
> +setInterval(updateCountdown, 1000);
я попытался. запутано. Но вроде работает. Но может есть способ легче?

2023-07-11 20:38 UTC, FryOS commented on 4-timer/app.js
> +  const YEAR_IN_MOUNTHS = 1000 * 60 * 60 * 24 * 30;
а что можно предложить? 
в инете вот такое решение видел. 
function daysInMonth(year, month) {
            let array = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
            return (month === 2 && DateExt.isLeapYear(year)) ? 29 : array[month - 1];
        }
        
        
вы когда говорите что надо высчиытвать вы что именно имеете ввиду? те константы что я вычисляю неверны?

2023-07-14 16:02 UTC, Grinv requested changes

2023-07-14 16:02 UTC, Grinv commented on 4-timer/app.js
> +if (trueNY) {
А есть не тру новый год?)
Лучше все булевый значения начинать с префикса типа `is` или `has` или `should` и т.д.
В данной случае можно использовать типа `isNewYearHappened`

2023-07-14 16:02 UTC, Grinv commented on 4-timer/app.js
> +function printTimeUntilNewYear(time) {
Оно ж не печатает, а возвращает, поэтому `get...`
Например `getCountdownText`

2023-07-14 16:02 UTC, Grinv commented on 4-timer/app.js
> +  clearInterval(interval);
У тебя ж никогда не остановится счетчик. Интерпретатор сюда приходит только один раз.
Тебе нужно проверять на то, нужно ли очищать интервал внутри функции, которую интервал вызывает
```javascript
let intervalId = setInterval(someFunction, 1000);

function someFunction {
   if (someCondidtion) {
      clearInterval(intervalId);
   }
}

2023-07-14 16:02 UTC, Grinv commented on 4-timer/app.js
> +  timeUntilNY.months === 0;
Первое - это не совсем точно. setInterval же не ровно через 1 секунду срабатывает, там всегда есть какое-то смещение, которое постепенно увеличивается. Поэтому лучше так сторого не сравнивать и обезопасить себя
```javascript
timeUntilNY.seconds <= 0 && timeUntilNY.minutes <= 0...
```

Второе - можно проще. Возьми разницу в timestamp между текущей датой и новым годов и узнаешь, зашли мы за дату или нет.

2023-07-14 16:02 UTC, Grinv commented on 4-timer/app.js
> +  countdown.textContent = countDownTimer;
Вот выглядит гораздо лучше)

2023-07-14 16:02 UTC, Grinv commented on 4-timer/app.js
> +const YEAR_IN_MINUTES = 1000 * 60;
Ты понимаешь смысл фразы YEAR_IN_MINUTES? Она обозначает сколько минут в году. Разве в году 60000 минут?

2023-07-14 16:02 UTC, Grinv commented on 4-timer/app.js
> +const YEAR_IN_MOUNTHS = 1000 * 60 * 60 * 24 * 30;
В году в роде 12 месяцев, а не 1000 * 60 * 60 * 24 * 30;

2023-07-14 16:02 UTC, Grinv commented on 4-timer/app.js
> +const YEAR_IN_SECONDS = 1000;
У тебя ни один нейминг не правильный)

2023-07-14 16:02 UTC, Grinv commented on 4-timer/app.js
> +  const days = Math.floor(diff / YEAR_IN_DAYS) % 30;
Пропустил комментарий. По прежнему месяцы считаются некорректно.

2023-07-14 20:23 UTC, FryOS commented on 4-timer/app.js
> +  const days = Math.floor(diff / YEAR_IN_DAYS) % 30;
так я не пропустил. я не знаю как сделать и как лучше сделать? есть мысли?

2023-07-20 04:58 UTC, Grinv commented on 4-timer/app.js
> +  const days = Math.floor(diff / YEAR_IN_DAYS) % 30;
https://bobbyhadz.com/blog/javascript-get-number-of-days-in-month
Статья, как подсказка ;)

2023-07-20 05:01 UTC, Grinv commented on 4-timer/app.js
> +  const YEAR_IN_SECONDS = 1000;
Каждый раз, когда ты вызываешь функцию, у тебя объявляется переменная. Есть ли смысл в этих действиях, если мы знаем, что переменная никогда не будет меняться? так мы можем немного оптимизировать наш код и превратить
```javascript
function someFunc() {
   const MY_CONTSANT = 'test';
   console.log(MY_CONTSANT);
}
```
в
```javascript
const MY_CONTSANT = 'test';

function someFunc() {
   console.log(MY_CONTSANT);
}

2023-07-20 05:08 UTC, Grinv commented on 4-timer/app.js
> +  const YEAR_IN_MOUNTHS = 1000 * 60 * 60 * 24 * 30;
Нет, я говорю про неправильный нейминг
Что значит фраза YEAR_IN_MOUNTHS? Сколько месяцев содержится в году. Кажется, их было всего 12, а не `1000 * 60 * 60 * 24 * 30`
Тебе же надо посчитать например, сколько миллисекунд содержится в дне? Миллисекунд в дне. Переводим. Получется. MILLISECONDS_IN_DAY.
Сколько миллисекунд в дней? Давай посчитаем. 1000 (1 секунда)  * 60 (1 минута) * 60 (1 час) * 24 (1 день)
Соотвественно у нас получается  
`const MILLISECONDS_IN_DAY = 1000 * 60 * 60 * 24;`
И так со всеми константами

2023-07-20 05:13 UTC, Grinv commented on 4-timer/app.js
> +setInterval(updateCountdown, 1000);
Очищать интервал как-то, кроме clearInterval? Нет. Либо так, либо использовать setTimeout

2023-07-20 05:15 UTC, Grinv requested changes

2023-07-20 05:15 UTC, Grinv commented on 4-timer/app.js
> +const trueNY =
Почему тут? Нам необходимо делать проверку, достигли ли мы НГ каждый раз когда вызываем updateCounter и если достигли, то останавливать счётчик

2023-08-05 11:47 UTC, Grinv requested changes

2023-08-05 11:47 UTC, Grinv commented on 4-timer/app.js
> +const currentYear = dateNow.getFullYear();
Можно ж переиспользовать `currentYear`
```javascript
const dateNow = new Date();
const currentYear = dateNow.getFullYear();
const newYear = new Date(currentYear + 1, 0, 1);

2023-08-05 11:47 UTC, Grinv commented on 4-timer/app.js
> +const currentMonth = dateNow.getMonth() + 1;
Зачем? Нигде не используется

2023-08-05 11:47 UTC, Grinv commented on 4-timer/app.js
> +  return `${time.months} месяцев ${time.days} дней ${time.hours} чсасов ${time.minutes} минут ${time.seconds} секунд`;
А как же склонение? 1 месяц, 2 месяца, 5 месяцев. С остальными также
Давай напишем функцию, которая правильно склоняет слова

2023-08-05 11:47 UTC, Grinv commented on 4-timer/app.js
> +  timeUntilNY.months === 0;
Не исправлено

2023-08-05 11:47 UTC, Grinv commented on 4-timer/app.js
> +if (trueNY) {
Не исправлено

2023-08-05 11:47 UTC, Grinv commented on 4-timer/app.js
> +  clearInterval(interval);
Не исправлено

2023-08-05 11:47 UTC, Grinv commented on 4-timer/app.js
> +  return (month === 2 && DateExt.isLeapYear(year)) ? 29 : array[month - 1];
Можешь воспользоваться статьёй https://bobbyhadz.com/blog/javascript-get-number-of-days-in-month
И сделать код чутка проще)

2023-08-05 11:47 UTC, Grinv commented on 4-timer/app.js
> +  const oneDay = 1000 * 60 * 60 * 24;
Т.к. это константа неизменная, лучше выносить её за функцию и писать через uppercase
const ONE_DAY = 1000 * 60 * 60 * 24;

2023-08-05 11:47 UTC, Grinv commented on 4-timer/app.js
> +  const months = Math.floor(diff / 1000/60/60/24/30);
Лучше тоже вынести в константу

2023-08-05 11:49 UTC, Grinv commented
Нажимай пожалуйста "Resolve conversation" на комментариях, которые исправил. Сложно становится читать.

2023-08-07 20:12 UTC, FryOS commented on 4-timer/app.js
> +if (trueNY) {
исправил

2023-08-07 20:13 UTC, FryOS commented on 4-timer/app.js
> +function printTimeUntilNewYear(time) {
ОК

2023-08-07 20:14 UTC, FryOS commented on 4-timer/app.js
> +  timeUntilNY.months === 0;
ОК

2023-08-07 20:17 UTC, FryOS commented on 4-timer/app.js
> +const currentMonth = dateNow.getMonth() + 1;
Все Используется

2023-08-07 20:19 UTC, FryOS commented on 4-timer/app.js
> +  return (month === 2 && DateExt.isLeapYear(year)) ? 29 : array[month - 1];
мой вариант лучше. Не хотелось бы использовать из статьи

2023-08-07 20:22 UTC, FryOS commented on 4-timer/app.js
> +  const oneDay = 1000 * 60 * 60 * 24;
OK

2023-08-07 20:29 UTC, FryOS commented on 4-timer/app.js
> +  const months = Math.floor(diff / 1000/60/60/24/30);
OK

2023-08-07 20:29 UTC, FryOS commented on 4-timer/app.js
> +const currentYear = dateNow.getFullYear();
OK

2023-08-07 20:41 UTC, FryOS commented on 4-timer/app.js
> +  const YEAR_IN_DAYS = 1000 * 60 * 60 * 24;
Убрал

2023-08-07 20:42 UTC, FryOS commented on 4-timer/app.js
> +  clearInterval(interval);
Чет не понимаю. Почему? Он его подчистит же

2023-08-07 20:42 UTC, FryOS commented on 4-timer/app.js
> +  countdown.textContent = countDownTimer;
OK

2023-08-07 20:52 UTC, FryOS commented on 4-timer/app.js
> +  return `${time.months} месяцев ${time.days} дней ${time.hours} чсасов ${time.minutes} минут ${time.seconds} секунд`;
Ok

2023-08-09 07:11 UTC, FryOS commented on 4-timer/app.js
> +  clearInterval(interval);
Понял кажется как решить проблему, типа такого кода надо проверить

// повторить с интервалом 2 секунды
let timerId = setInterval(() => alert('tick'), 2000);

// остановить вывод через 5 секунд
setTimeout(() => { clearInterval(timerId); alert('stop'); }, 5000);

буду пробовать.

2023-08-10 17:21 UTC, Grinv commented on 4-timer/app.js
> +  clearInterval(interval);
Нет, я ж выше код написал)
```javascript
let intervalId = setInterval(someFunction, 1000);

function someFunction {
   if (someCondidtion) {
      clearInterval(intervalId);
   }
}
```
вызываешь интервал, его идентификатор сохраняешь в переменную. При вызове из интервала функции, внутри самой функции проверяешь, а нужно ли ещё раз вызывать её. Если нет - отменяешь интервал (clearInterval), если ещё надо вызвать - ничего не делаешь)

2023-08-10 17:27 UTC, Grinv requested changes

2023-08-10 17:27 UTC, Grinv commented on 4-timer/app.js
> +const interval = setInterval(updateCountdown, 1000);
Тебе этот интервал надо чистить внутри updateCountdown, а не на 99 строке.

Если не можешь понять - пиши в личку, я расскажу)

2023-08-10 17:27 UTC, Grinv commented on 4-timer/app.js
> +function declOfNum(n, text_forms) {
Давай пользоваться современными методами) Intl.PluralRules. Если вдруг английский язык будет, то твой код автоматически не будет работать
Я уже скидывал страницу, на которой рассказывается, как это сделать: https://2ality.com/2019/12/intl-pluralrules.html

2023-08-10 17:27 UTC, Grinv commented on 4-timer/app.js
> +  return month === 2 && DateExt.isLeapYear(year) ? 29 : array[month - 1];
Я ж присылал пример, как понять, сколько у тебя дней в месяце. Давай воспользуемся
https://bobbyhadz.com/blog/javascript-get-number-of-days-in-month

2023-08-20 21:22 UTC, FryOS commented on 4-timer/app.js
> +  return month === 2 && DateExt.isLeapYear(year) ? 29 : array[month - 1];
Я понял, я видел статью. Но этот код понятнее

2023-08-21 20:31 UTC, FryOS commented on 4-timer/app.js
> +  clearInterval(interval);
Ок. сделал как ты сказал. но не понимаю почему это так должно работать

2023-08-21 20:33 UTC, FryOS commented on 4-timer/app.js
> +function declOfNum(n, text_forms) {
я пока не хочу перегружать код и себя новыми вещами. Давай остановимся на том что есть. я так не успеваю

2023-08-24 23:34 UTC, Grinv requested changes

2023-08-24 23:34 UTC, Grinv commented on 4-timer/app.js
> +const timeUntilNY = getTimeUntilNewYear();
Удалить

2023-08-24 23:34 UTC, Grinv commented on 4-timer/app.js
> +const IsNewYear =
Это тоже удалить. Зачем столько мусора оставил?

2023-08-24 23:34 UTC, Grinv commented on 4-timer/app.js
> +function someFunction() {
И это всё убрать. Я тут сидел минут 5 разбирался, зачем это всё. Разве не жалко времени ревьювера?)

2023-08-24 23:34 UTC, Grinv commented on 4-timer/app.js
> +  ${time.seconds} ${declOfNum(time.months, ["секунд", "секунда", "секунды"])}`;
["секунда", "секунды", "секунд"]

2023-08-24 23:34 UTC, Grinv commented on 4-timer/app.js
> +function someFunction() {
У тебя же эта функция нигде не вызывается

2023-08-24 23:34 UTC, Grinv commented on 4-timer/app.js
> +const intervalId = setInterval(updateCountdown, 1000);
А какой смысл тогда создавать идентификатор интервала, если ты его нигде не применяешь?

2023-08-24 23:34 UTC, Grinv commented on 4-timer/app.js
> +}
Посмотри пожалуйста примеры в статье
https://www.w3schools.com/jsref/met_win_clearinterval.asp

2023-08-26 20:23 UTC, FryOS commented on 4-timer/app.js
> +const timeUntilNY = getTimeUntilNewYear();
как это удалить если оно используется!

2023-08-26 20:24 UTC, FryOS commented on 4-timer/app.js
> +const IsNewYear =
Почему мусор?

2023-08-26 20:24 UTC, FryOS commented on 4-timer/app.js
> +  ${time.seconds} ${declOfNum(time.months, ["секунд", "секунда", "секунды"])}`;
Перепутал

2023-08-26 20:24 UTC, FryOS commented on 4-timer/app.js
> +const intervalId = setInterval(updateCountdown, 1000);
Применяю.

2023-08-26 20:28 UTC, FryOS commented on 4-timer/app.js
> +}
Разве мой вариант не работает?

2023-08-26 20:29 UTC, FryOS commented on 4-timer/app.js
> +function someFunction() {
зачем? Что именно не ясно?

2023-08-27 12:38 UTC, Grinv requested changes

2023-08-27 12:38 UTC, Grinv commented on 4-timer/app.js
> +function someFunction() {
Зачем тут эта функция? someFunction вообще надо удалить, она была мной дана ради примера общей логики. Тебе надо такую же логику применить в updateCountdown

2023-08-27 19:51 UTC, FryOS commented on 4-timer/app.js
> +function someFunction() {
Я что-то запутался. Ты приводишь пример. Но по итогу я делаю сам, это неправильно, потом ты говоришь вот же функция, я делаю ее. И теперь ты говоришь это пример, переделай. Так как верно то?

2023-08-31 17:33 UTC, Grinv commented
https://github.com/FryOS/js-test-1/pull/36/files
Поправил интервал и склонения.
Держи фикс, можешь посмотреть и если есть вопросы - можешь задать

2023-10-06 16:52 UTC, Grinv commented on 4-timer/app.js
> +function someFunction() {
Ты понимаешь значение слова "пример"?
Пример - это похожий кейс/случай. Я тебе показал, как в общем оно должно работать, общую структуру и логику, зачем мне писать код за тебя? И тебя не смутили названия функций "someFunction"?

2023-10-06 16:52 UTC, Grinv approved these changes

2023-10-06 16:52 UTC, merged