наследование на прототипах
FryOS/js-test-1 pull request #25
Opened 2023-07-10 18:26 UTC by FryOS

наследование на прототипах

2023-07-14 16:07 UTC, Grinv requested changes

2023-07-14 16:07 UTC, Grinv commented on 5-oop/app.js
> +Ork.prototype.toHit = function () {
Просто `hit`

2023-07-14 16:07 UTC, Grinv commented on 5-oop/app.js
> +const ork = new Ork('ork', 'рыжий', "орчий", true );
А почему ты вместо оружия true передаёшь? Ты ж должен название оружия передавать и потом его выводить, когда бьёшь, типа `Орк бьёт оружием "Топор"`
С эльфом тоже самое

2023-07-14 16:07 UTC, Grinv commented on 5-oop/app.js
> +console.log(elf);
Круто, молодец. Почти всё правильно сделал)

2023-07-14 20:22 UTC, FryOS commented on 5-oop/app.js
> +const ork = new Ork('ork', 'рыжий', "орчий", true );
я делаю true потому что идея была что оружие есть

2023-07-16 16:17 UTC, FryOS commented on 5-oop/app.js
> +Ork.prototype.toHit = function () {
Вот почему? Сами ведь говорили что действие оно типа toHit, а тут обратное?

2023-07-16 16:19 UTC, FryOS commented on 5-oop/app.js
> +const ork = new Ork('ork', 'рыжий', "орчий", true );
Ок переделал

2023-07-16 16:19 UTC, FryOS commented on 5-oop/app.js
> +console.log(elf);
А то =))

2023-07-18 07:57 UTC, Grinv commented on 5-oop/app.js
> +Ork.prototype.toHit = function () {
Всё верно. hit - это глагол, всё ок, артиклей не надо.

2023-07-18 08:10 UTC, Grinv requested changes

2023-07-18 08:10 UTC, Grinv commented on 5-oop/app.js
> +  console.log("I hit you!");
Давай ещё у орка и эльфа выведем название оружия/заклинания, чем они бьют

2023-07-21 19:59 UTC, FryOS commented on 5-oop/app.js
> +  console.log("I hit you!");
Переделал

2023-07-27 06:22 UTC, Grinv approved these changes

2023-07-27 06:22 UTC, merged