OOP class
FryOS/js-test-1 pull request #26
Opened 2023-07-11 21:19 UTC by FryOS

2023-07-14 16:11 UTC, Grinv requested changes

2023-07-14 16:11 UTC, Grinv commented on 6-class/app.js
> +  get getMileage() {
Геттеры и сеттеры пишем без get и set в названии
```javascript
set mileage(mileage) {
   this.#mileage = mileage;
}

get mileage() {
   return this.#mileage;
}

2023-07-14 16:11 UTC, Grinv commented on 6-class/app.js
> +    this.#mileage = mileage;
Лучше сразу заиспользуй тут сеттер, раз уже он у нас есть)

2023-07-14 16:11 UTC, Grinv commented on 6-class/app.js
> +console.log(car.getInfo());
Good job!👍

2023-07-16 16:07 UTC, FryOS commented on 6-class/app.js
> +  get getMileage() {
Ну я бы поспорил, ибо не ясно что это. Называются одинаково. Человек может запутаться. Ну ок. раз так.

2023-07-16 16:15 UTC, FryOS commented on 6-class/app.js
> +    this.#mileage = mileage;
оки

2023-07-16 16:15 UTC, FryOS commented on 6-class/app.js
> +console.log(car.getInfo());
Еееее

2023-07-18 07:59 UTC, Grinv commented on 6-class/app.js
> +  get getMileage() {
Спорь тогда с мировым сообществом, а не со мной) Это как бы стандарт такой.

2023-07-18 08:03 UTC, Grinv approved these changes

2023-07-18 08:03 UTC, Grinv commented on 6-class/app.js
> +    return this.#_mileage;
Не надо и hash и underscope символы одновременно применять. Выбери что-то одно)

2023-07-18 08:03 UTC, merged