sOlid
FryOS/js-test-1 pull request #27
Opened 2023-07-13 19:12 UTC by FryOS

O - пример реализации

2023-07-15 12:15 UTC, Grinv requested changes

2023-07-15 12:15 UTC, Grinv commented on 8-solid/app.js
Тут вся логика заключается в том, что в конструктор класса мы прокидываем amount (стоимость продукта)

А потом в calculateTotal созданного инстанса прокидываем сколько всего штук/часов надо посчитать. И в зависимости от типа расчёта нам возвращается та или иная сумма

2023-07-15 12:15 UTC, Grinv commented on 8-solid/app.js
> +}
А где примеры и тесты?)

2023-07-15 12:15 UTC, Grinv commented on 8-solid/app.js
> +    return this.amount;
Откуда ты this.amount берёшь?

2023-07-15 12:15 UTC, Grinv commented on 8-solid/app.js
> +    return this.amount * discountAmount;
Что за discount?)
Как вариант расчёт - при создании класса мы прокидываем сколько стоит 1 отработанный час.
А потом в calculateTotal прокидываем, сколько минут работник отработал, считаем результат и возвращаем.

2023-07-15 12:15 UTC, Grinv commented on 8-solid/app.js
> +    return this.amount * itemBilling;
Формула верная, но опять же, откуда ты this.amount берёшь?)

2023-07-15 12:15 UTC, Grinv commented on 8-solid/app.js
> +    this.amount += amount;
Почему так? Мы ж не знаем точно, какой расчёт у нас) 
Я б тут заглушку оставил.
```javascript
class Billing {
   constructor(amount) {
      this.amount = amount;
   }

   calculateTotal() {}
}

2023-07-15 12:15 UTC, Grinv commented on 8-solid/app.js
> +  amount;
Смысл в такой записи какой?)
Не сохраняешь, не объявляешь, не типизируешь.

Давай amount в конструкторе при создании инстанса сохранять.

2023-07-16 15:21 UTC, FryOS commented on 8-solid/app.js
> +}
Какие примеры и тесты?

2023-07-16 15:59 UTC, FryOS commented on 8-solid/app.js
> +    return this.amount * discountAmount;
discount - это просто пример рандомный, Ибо в задании ну указано, что должно быть. Вот сделал такой пример кода.

2023-07-16 15:59 UTC, FryOS commented on 8-solid/app.js
> +    return this.amount * itemBilling;
переделал

2023-07-16 16:01 UTC, FryOS commented on 8-solid/app.js
> +    this.amount += amount;
Пусть будет по вашему

2023-07-16 16:01 UTC, FryOS commented on 8-solid/app.js
> +  amount;
Давай.

2023-07-21 19:55 UTC, FryOS commented on 8-solid/app.js
Так и есть. сейчас все как надо по заданию работает.

2023-07-24 09:47 UTC, Grinv requested changes

2023-07-24 09:47 UTC, Grinv commented on 8-solid/app.js
> +}
Примеры того, как ты создаешь инстансы остальных классов

2023-07-24 09:47 UTC, Grinv commented on 8-solid/app.js
> +  amount = 3;
Хардкод) А если нам надо другое количество товаров?
Нужно amount передавать в конструктор, а itemBilling в calculateTotal
Тогда у тебя будет более гибкая система
С остальными также.

2023-07-24 13:23 UTC, FryOS commented on 8-solid/app.js
> +  amount = 3;
Переделал конструктор

2023-07-24 13:23 UTC, FryOS commented on 8-solid/app.js
> +}
переделал

2023-07-27 06:22 UTC, Grinv approved these changes

2023-07-27 06:22 UTC, merged