XMLHttpRequest
FryOS/js-test-1 pull request #29
Opened 2023-07-16 20:55 UTC by FryOS

pokemon

2023-07-18 08:19 UTC, Grinv requested changes

2023-07-18 08:19 UTC, Grinv commented on 9-pokemon/app.js
> +});
Помним про solid и переиспользуемость.
Давай превратим это в функцию, которую мы будем вызывать, когда хотим и она нам будет возвращать информацию по запрошенному покемону.

2023-07-21 19:42 UTC, FryOS commented on 9-pokemon/app.js
> +});
Привет, я сделал. Но ты можешь проверить правильно ли? Хотел выделить отправку запроса в отдельный метод. Но не вышло. Сделал все в одной пока функции
Так делать правильно?

2023-07-27 06:41 UTC, Grinv commented on 9-pokemon/app.js
> +});
Ну смотри
1) Нам необходимо прокинуть функцию коллбэк, чтоб мы могли что угодно делать с нашими данными. Стандартная схема такая:
```javascript
function fetch(callback) {
   // какой-то код и получаем результат "data"
   if(callback) {
      callback(data);
   }
}
```
Давай перепишем наш код:
```javascript
function getPokemonData(callback) {
  const request = new XMLHttpRequest();
  request.open("GET", "https://pokeapi.co/api/v2/pokemon/ditto");

  request.send();  

   request.addEventListener("load", function (e) {
    const { abilities } = JSON.parse(request.responseText);
    const newUrl = abilities[0].ability.url;

    const request1 = new XMLHttpRequest();
    request1.open("GET", newUrl);
    request1.send();

    request1.addEventListener("load", function (e) {
      const { effect_entries } = JSON.parse(request1.responseText);

      const { effect } = effect_entries[1];
      if (typeof callback === 'function') {
      	callback(effect);
      }
    });
  });
}

function consoleData(data) {
      	console.log(data);
}

getPokemonData(consoleData);
```

2) Возможно, что нам надо получить ещё инфу и по другому покемону, пикачу например. Писать ещё функцию? Зачем, у нас же есть уже. Давай сделаем её более универсальной и будем передавать покемона, который нам нужен
```
const POKEMON_INFO_URL = "https://pokeapi.co/api/v2/pokemon";

function getPokemonData(pokemonName, callback) {
  const request = new XMLHttpRequest();
  request.open("GET", `${POKEMON_INFO_URL}/${pokemonName}`);

  request.send();  

   request.addEventListener("load", function (e) {
    const { abilities } = JSON.parse(request.responseText);
    const newUrl = abilities[0].ability.url;

    const request1 = new XMLHttpRequest();
    request1.open("GET", newUrl);
    request1.send();

    request1.addEventListener("load", function (e) {
      const { effect_entries } = JSON.parse(request1.responseText);

      const { effect } = effect_entries[1];
      if (typeof callback === 'function') {
      	callback(effect);
      }
    });
  });
}

function consoleData(data) {
	console.log(data);
}

function alertData(data) {
	alert(data);
}

getPokemonData('ditto', consoleData);
getPokemonData('pikachu', alertData);
```
Вот и смотри, какая гибкая функция у нас получилась, в которую мы можем передавать и имя нужного покемона и что с ним делать. А кода почти не прибавилось :)

2023-07-27 06:44 UTC, Grinv requested changes

2023-07-27 06:44 UTC, Grinv commented on 9-pokemon/app.js
> +getPokemonData();
Отписался под твоим комментарием
https://github.com/FryOS/js-test-1/pull/29#discussion_r1275800189

2023-07-30 16:34 UTC, FryOS commented on 9-pokemon/app.js
> +});
Уиииииии вышло

2023-08-05 11:50 UTC, Grinv approved these changes

2023-08-05 11:50 UTC, Grinv commented on 9-pokemon/app.js
> +
Да, всё правильно понял) Отличная работа!

2023-08-05 11:50 UTC, merged