ДЗ fetch
FryOS/js-test-1 pull request #30
Opened 2023-07-17 14:24 UTC by FryOS

2023-07-18 08:22 UTC, Grinv requested changes

2023-07-18 08:22 UTC, Grinv commented on 10-pokemon-promise/app.js
> +//const fetch = require ("node-fetch")
Лишние комментарии

2023-07-18 08:22 UTC, Grinv commented on 10-pokemon-promise/app.js
> +  .catch((error) => console.log(error));
Тоже самое, что и с прошлый заданием. Давай сделаем функцию, которую можем вызвать в любой момент и дальше уже сами будем решать, что делать с тем, что она вернёт. Может я захочу не законсолить, а что-то другой с данными сделать.

2023-07-21 19:09 UTC, FryOS commented on 10-pokemon-promise/app.js
> +//const fetch = require ("node-fetch")
У меня не работал фетч, пришлось его ставить, потом я узнал в версии 18 ноды он работает. короче забыл по итогу убрать.

2023-07-21 19:12 UTC, FryOS commented on 10-pokemon-promise/app.js
> +  .catch((error) => console.log(error));
Давай. +)

2023-07-27 06:50 UTC, Grinv requested changes

2023-07-27 06:50 UTC, Grinv commented on 10-pokemon-promise/app.js
> +console.log(getPokemonData(pokeUrl));
Попробуй сделать примерно, как я описал в предыдущем задании с покемонами (https://github.com/FryOS/js-test-1/pull/29#discussion_r1275800189)
Но у тебя тут промис, так что не через колбэк надо будет сделать, а через нативные инструменты промиса :)
Нужно, чтоб функция вызова по итогу выглядела вот так:
```javascript
getPokemonData('pikachu').then(consoleData);

2023-08-05 11:52 UTC, merged

2023-08-05 11:52 UTC, Grinv commented on 10-pokemon-promise/app.js
> +  const url = "https://pokeapi.co/api/v2/pokemon"
Лучше вынести за функцию, может где-то понадобиться.

2023-08-05 11:52 UTC, Grinv commented on 10-pokemon-promise/app.js
> +getPokemonData("pikachu").then(alertData).catch(console.error);
Да, сделал, как надо. Молодец! 👍