Кликер кнопок
FryOS/js-test-1 pull request #33
Opened 2023-08-02 19:19 UTC by FryOS

2023-08-05 12:00 UTC, Grinv requested changes

2023-08-05 12:00 UTC, Grinv commented on 13-buttons/app.js
> +  button.addEventListener('click', function() {
Зачем? Мы ж специально сделали делегирование событий, чтоб не навешивать события на кнопки
У нас должно висеть только одно событие на wrapper и его нужно обрабатывать

2023-08-05 12:00 UTC, Grinv commented on 13-buttons/app.js
> +    element.setAttribute("data-id", i);
Зачем тебе этот атрибут? Он у нас нигде не используется

2023-08-07 20:57 UTC, FryOS commented on 13-buttons/app.js
> +  button.addEventListener('click', function() {
Я пытался решить иначе. Не смог. Я не вижу пока что другого варианта как это сделать . Шерстил инет. Делают так. Жду помощи тогда.

2023-08-07 20:57 UTC, FryOS commented on 13-buttons/app.js
> +    element.setAttribute("data-id", i);
Я его пробовал юзать В итоге сделал иначе

2023-08-10 17:28 UTC, Grinv requested changes

2023-08-10 17:28 UTC, Grinv commented on 13-buttons/app.js
> +  button.addEventListener('click', function() {
Напиши в личку тогда, давай обсудим

2023-08-24 23:19 UTC, Grinv requested changes

2023-08-24 23:19 UTC, Grinv commented on 13-buttons/index.html
> +
Нет закрывающего тэга для wrapper

2023-08-24 23:19 UTC, Grinv commented on 13-buttons/app.js
> +  for (let i = 0; i < buttons.length; i++) {
А зачем ты все кнопки перебираешь? У тебя в событии уже лежит нужная кнопка)
```javascript
wrapper.addEventListener("click", function (e) {
   if (e.target.classList.contains("button")) {
      e.target.textContent = "нажата";
   }
});

2023-08-24 23:19 UTC, Grinv commented on 13-buttons/app.js
> +  }
А как же отжать те кнопки, которые были раньше нажаты?)

2023-08-24 23:19 UTC, Grinv commented on 13-buttons/app.js
> +wrapper.addEventListener('click', function() {
Давай объединим всё в один слушателей. Нет смысла 2 шутки создавать

2023-08-24 23:19 UTC, Grinv commented on 13-buttons/app.js
> +wrapper.addEventListener("click", function (e) {
Да, ты правильно понял делегирование, молодец)

2023-08-26 20:34 UTC, FryOS commented on 13-buttons/index.html
> +
Сорри

2023-08-26 20:36 UTC, FryOS commented on 13-buttons/app.js
> +  for (let i = 0; i < buttons.length; i++) {
От прошлого кода осталось.

2023-08-26 20:36 UTC, FryOS commented on 13-buttons/app.js
> +  }
А такого не было задания, и зачем их отжимать?

2023-08-26 20:37 UTC, FryOS commented on 13-buttons/app.js
> +wrapper.addEventListener('click', function() {
ХМ и правда это работает. Давай

2023-08-26 20:37 UTC, FryOS commented on 13-buttons/app.js
> +wrapper.addEventListener("click", function (e) {
Уиииииии

2023-08-27 12:35 UTC, Grinv commented
Ничего не поправлено

2023-08-31 17:00 UTC, Grinv approved these changes
Да, хорошо. В качестве самостоятельной работы подумай, как нам можно отжимать кнопки, если следующей мы жмём не их. Т.е. нажимаем кнопку - она меняется на "Нажата". Нажимаем на другую - меняет своё состояние обратно на "Нажми меня"

2023-10-03 19:27 UTC, merged